# Generated by Django 4.2.7 on 2025-08-15 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('workflow_update', 'Workflow Update'), ('budget_alert', 'Budget Alert'), ('stock_alert', 'Stock Alert'), ('approval_request', 'Approval Request'), ('deadline_reminder', 'Deadline Reminder'), ('system_update', 'System Update')], max_length=20)),
                ('subject_template', models.CharField(help_text='Subject line template with variables', max_length=255)),
                ('body_template', models.TextField(help_text='Body template with variables')),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('both', 'Both')], default='both', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('available_variables', models.JSONField(default=list, help_text='List of available template variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('trigger_event', models.CharField(choices=[('workflow_state_change', 'Workflow State Change'), ('budget_variance', 'Budget Variance'), ('stock_low', 'Stock Low'), ('deadline_approaching', 'Deadline Approaching'), ('user_action', 'User Action')], max_length=25)),
                ('conditions', models.JSONField(default=dict, help_text='Conditions that must be met')),
                ('recipient_roles', models.JSONField(default=list, help_text='Roles to notify')),
                ('delay_minutes', models.IntegerField(default=0, help_text='Delay before sending')),
                ('max_frequency_hours', models.IntegerField(default=24, help_text='Minimum hours between same notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notification_rules', to=settings.AUTH_USER_MODEL)),
                ('specific_users', models.ManyToManyField(blank=True, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('workflow_submitted', models.BooleanField(default=True)),
                ('workflow_approved', models.BooleanField(default=True)),
                ('workflow_rejected', models.BooleanField(default=True)),
                ('workflow_comments', models.BooleanField(default=True)),
                ('budget_alerts', models.BooleanField(default=True)),
                ('budget_variance', models.BooleanField(default=True)),
                ('budget_deadlines', models.BooleanField(default=True)),
                ('stock_alerts', models.BooleanField(default=True)),
                ('stock_requests', models.BooleanField(default=True)),
                ('system_updates', models.BooleanField(default=True)),
                ('maintenance_alerts', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=10)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('context_data', models.JSONField(default=dict, help_text='Data used to render the template')),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sent', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('workflow_notifications', models.IntegerField(default=0)),
                ('budget_notifications', models.IntegerField(default=0)),
                ('stock_notifications', models.IntegerField(default=0)),
                ('system_notifications', models.IntegerField(default=0)),
                ('average_read_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('read_rate_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_stats',
                'ordering': ['-date'],
                'unique_together': {('date', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('retried', 'Retried')], max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Additional event data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification', 'event_type'], name='notificatio_notific_324e22_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notifications', models.ManyToManyField(related_name='digests', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_digests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'digest_type'], name='notificatio_user_id_a760cd_idx'), models.Index(fields=['period_start', 'period_end'], name='notificatio_period__c02d5e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_218e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'status'], name='notificatio_priorit_f26a58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_3d00b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_1106fe_idx'),
        ),
    ]
