# Generated by Django 4.2.7 on 2025-08-15 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('stock_request', 'Stock Request'), ('budget_approval', 'Budget Approval'), ('forecast_inquiry', 'Forecast Inquiry'), ('supply_chain', 'Supply Chain'), ('general', 'General'), ('system_alert', 'System Alert')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notifications.message')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notificationdigest',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='notificationdigest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='specific_users',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='template',
        ),
        migrations.AlterUniqueTogether(
            name='notificationstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationstats',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationDigest',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
        migrations.DeleteModel(
            name='NotificationRule',
        ),
        migrations.DeleteModel(
            name='NotificationStats',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
    ]
