# Generated by Django 4.2.7 on 2025-08-15 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sales_budget', 'Sales Budget'), ('rolling_forecast', 'Rolling Forecast')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by_role', models.CharField(max_length=20)),
                ('current_state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_to_supply_chain', 'Sent to Supply Chain')], default='draft', max_length=25)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_supply_chain_at', models.DateTimeField(blank=True, null=True)),
                ('customers', models.JSONField(default=list, help_text='List of customer names')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('year', models.CharField(max_length=4)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('budget_data', models.JSONField(blank=True, default=list, help_text='YearlyBudgetData array')),
                ('forecast_data', models.JSONField(blank=True, default=list, help_text='ForecastData array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workflow_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflow_items', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_workflow_items', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workflow_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('workflow_type', models.CharField(choices=[('sales_budget', 'Sales Budget'), ('rolling_forecast', 'Rolling Forecast')], max_length=20)),
                ('default_approvers', models.JSONField(default=list, help_text='List of default approver roles')),
                ('required_fields', models.JSONField(default=list, help_text='Required fields for this workflow')),
                ('auto_approval_rules', models.JSONField(default=dict, help_text='Rules for automatic approval')),
                ('notification_triggers', models.JSONField(default=dict, help_text='When to send notifications')),
                ('escalation_rules', models.JSONField(default=dict, help_text='Escalation after time periods')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('auto_approve', 'Auto Approve'), ('escalate', 'Escalate'), ('notify', 'Notify'), ('reject', 'Auto Reject')], max_length=15)),
                ('conditions', models.JSONField(default=dict, help_text='Conditions to trigger this rule')),
                ('actions', models.JSONField(default=dict, help_text='Actions to take when rule triggers')),
                ('workflow_types', models.JSONField(default=list, help_text='Which workflow types this applies to')),
                ('user_roles', models.JSONField(default=list, help_text='Which user roles this applies to')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_to_supply_chain', 'Sent to Supply Chain')], max_length=25)),
                ('to_state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_to_supply_chain', 'Sent to Supply Chain')], max_length=25)),
                ('action', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('data_snapshot', models.JSONField(default=dict, help_text='Workflow data before this change')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.workflowitem')),
            ],
            options={
                'db_table': 'workflow_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowComment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author_role', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('request_changes', 'Request Changes')], default='comment', max_length=20)),
                ('is_follow_back', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_comments', to=settings.AUTH_USER_MODEL)),
                ('workflow_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow.workflowitem')),
            ],
            options={
                'db_table': 'workflow_comments',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FollowBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_follow_backs', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_follow_backs', to=settings.AUTH_USER_MODEL)),
                ('workflow_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_backs', to='workflow.workflowitem')),
            ],
            options={
                'db_table': 'follow_backs',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('workflow_type', models.CharField(choices=[('sales_budget', 'Sales Budget'), ('rolling_forecast', 'Rolling Forecast')], max_length=20)),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('required_approvers', models.JSONField(default=list, help_text='List of required approver roles')),
                ('approval_levels', models.JSONField(default=list, help_text='Sequential approval levels')),
                ('customer_types', models.JSONField(blank=True, default=list, help_text='Applicable customer types')),
                ('departments', models.JSONField(blank=True, default=list, help_text='Applicable departments')),
                ('approval_deadline_hours', models.IntegerField(default=72, help_text='Hours to complete approval')),
                ('escalation_hours', models.IntegerField(default=48, help_text='Hours before escalation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_matrices',
                'ordering': ['min_value'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('recipient_role', models.CharField(max_length=20)),
                ('from_role', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('comment', 'Comment'), ('follow_back', 'Follow Back'), ('supply_chain_request', 'Supply Chain Request')], max_length=25)),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('workflow_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflow.workflowitem')),
            ],
            options={
                'db_table': 'workflow_notifications',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='workflow_no_recipie_fc0f96_idx'), models.Index(fields=['workflow_item', 'type'], name='workflow_no_workflo_4d8a46_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowitem',
            index=models.Index(fields=['current_state', 'type'], name='workflow_it_current_f83417_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowitem',
            index=models.Index(fields=['created_by', 'current_state'], name='workflow_it_created_afdc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowitem',
            index=models.Index(fields=['year', 'priority'], name='workflow_it_year_37d83f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['workflow_item', 'changed_at'], name='workflow_hi_workflo_40c65d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcomment',
            index=models.Index(fields=['workflow_item', 'timestamp'], name='workflow_co_workflo_2697a5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcomment',
            index=models.Index(fields=['author', 'type'], name='workflow_co_author__fe0bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='followback',
            index=models.Index(fields=['assigned_to', 'is_completed'], name='follow_back_assigne_bd069a_idx'),
        ),
        migrations.AddIndex(
            model_name='followback',
            index=models.Index(fields=['workflow_item', 'priority'], name='follow_back_workflo_0b6505_idx'),
        ),
    ]
