# Generated by Django 4.2.7 on 2025-08-14 11:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyBudget',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('yearly_budgets', models.JSONField(default=dict, help_text="Budget data for multiple years: {'2025': 1000, '2026': 1200}")),
                ('yearly_actuals', models.JSONField(default=dict, help_text="Actual data for multiple years: {'2025': 850, '2026': 0}")),
                ('yearly_values', models.JSONField(default=dict, help_text='Calculated values for multiple years')),
                ('budget_2025', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_2025', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_2026', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('git', models.IntegerField(default=0, help_text='Goods In Transit')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yearly Budget',
                'verbose_name_plural': 'Yearly Budgets',
                'db_table': 'yearly_budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('month_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('budget_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('git', models.IntegerField(default=0, help_text='Goods In Transit')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yearly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='budgets.yearlybudget')),
            ],
            options={
                'verbose_name': 'Monthly Budget',
                'verbose_name_plural': 'Monthly Budgets',
                'db_table': 'monthly_budgets',
                'ordering': ['yearly_budget', 'month_number'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('monthly_distribution', models.JSONField(default=dict, help_text='Monthly distribution percentages')),
                ('default_rates', models.JSONField(default=dict, help_text='Default rates by month')),
                ('seasonal_adjustments', models.JSONField(default=dict, help_text='Seasonal adjustment factors')),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], max_length=20)),
                ('previous_data', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yearly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='budgets.yearlybudget')),
            ],
            options={
                'db_table': 'budget_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('seasonal', 'Seasonal'), ('custom', 'Custom'), ('historical', 'Historical-based'), ('linear', 'Linear')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('january', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('february', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('march', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('april', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('may', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('june', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('july', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('august', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('september', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('october', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('november', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('december', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_distributions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('variance', 'Variance Alert'), ('approval', 'Approval Required'), ('deadline', 'Deadline Alert'), ('budget_exceeded', 'Budget Exceeded')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('yearly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.yearlybudget')),
            ],
            options={
                'db_table': 'budget_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='yearlybudget',
            index=models.Index(fields=['customer', 'year'], name='yearly_budg_custome_62b8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='yearlybudget',
            index=models.Index(fields=['created_by', 'status'], name='yearly_budg_created_9686dd_idx'),
        ),
        migrations.AddIndex(
            model_name='yearlybudget',
            index=models.Index(fields=['year', 'category'], name='yearly_budg_year_a7ecd0_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybudget',
            index=models.Index(fields=['yearly_budget', 'month_number'], name='monthly_bud_yearly__61d548_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybudget',
            unique_together={('yearly_budget', 'month')},
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['yearly_budget', 'changed_at'], name='budget_hist_yearly__0bc727_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['recipient', 'is_read'], name='budget_aler_recipie_ad0fff_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['alert_type', 'severity'], name='budget_aler_alert_t_982933_idx'),
        ),
    ]
